sudo: false
language: go
go:
- 1.4.2
install:
- go get github.com/laher/goxc > /dev/null 2> /dev/null
- go get github.com/rahulsom/mailcli
- goxc -t
- gem install asciidoctor
script: "./travis.sh"
env:
  global:
  - GIT_NAME="Rahul Somasunderam"
  - GIT_EMAIL="rahul.som@gmail.com"
  - secure: oFUmAO2vuj5vNUhj3R76eX5nbIDoMw5PSmYUsy+qdD8BXlDlkBdgXMHC6OLf5l6bQ6tVcMxJDlryZzUtH8U2+SUr4/25CBIEv9AUWLIlFSiWWxARa9xE4eQxCpancjVOMmaCeM1XCpuGS3zH4ZFJXiBpgt7KNax8jZb9NPJxgz0Ki39u5Rbykr2Q2HhvhDF3PufmCGDscxh2u9DShpRhydOD3/EIPnGvYNxZ6qjL5exDqEnHw333lURo2vTp1PpWj+VIkvdEH0bp7hwryRbha+u73iiFx3DyqlftuDuclgYwxxelABqwPnd/tfGtVnMLp/VGT27YJHyB1RETcFDw2Ywojvk8t2oe1uEUGXGNbf/qXgjcCfWSwS7fEK29tqja9AfLeKx2GBwo2/9YL6Le+yYIXyO5pAqeXVdl7v/cfgB0+MSia8jOBQCLUGJ4+iDSb+XhrCVd0cZI7ALQ1jRVhQqMCmDeFKMBekFuU8W3NkbU4JK9OdZPahcxnR6uxr4D1RGtQNXIlM3ZFS9zuiPmoC3sK86xexAFN8RwfJ0nX0pJSPmkerEU8QASBh09c4rZ2Ypc6JlWEu0HlzdJHjqkvgd/dUSpM6V8rKSZM2BfqWJqNr0U5Xx4wkHY5+boSKz4CazCAsBjL0cN+IFxgbCFRf1fNRza3d9dn2Rc0FAZPUY=
  - secure: sIiraJVCdsJ71s0o3FyzCoREyNSqq3tFKNNARUINAsA2XPu+LTTVRORUE2vIj7oJmGDNxtq+o6H7QRzslMT8DV5gZVc8zBG7SUfFx0ubRoVuvVt0DZDBMYMAtqPku880wrCMFYROBUpDkSMupH0g03P1gjUXlcQsE3QJSwnhoALeduRzzWUDf/4QuuVLVZfjYB5kJHVu6RlCbzy4hYb0MCzCaX+bbcbtK7qX/2i00KdMtJXhW13rwkBqvaMtJsGYzEeEOe779ejQVmWTmqm9haK34JN7CNyUcB82QuRa64lw4abtCPtIBEZXjnmnPRNBDIaCLCxUVWtuBRV0YT8IXgMWdfrxha5zNp/f+jKwHGNieHSIn0n56CnLhqZfl4WYzPw9fNaniVJxKBjZZJ5BJhPqFhjheZ+YynXh/nT9lNomse+xH++EozCOt5GK+Okmj37oya/y4+m6KeAFbL5T4gyw+uu9HvNJ1tEIn1+qt8r6IKk3z92T8WjF28UAUsShGWsJr+gBEFIToFBWt6oW0nZoSpnBeQWBPUyPgfIpVbMsN7PwarKdesY/3a5BclMEIl3ANvrPhdPrN3QDnp7ZEvCmz5nqOe56HCIFA7mpLcHlythKE67rhfYyzWHwAM9TUeY4aOLB7N5HzSz4T2Py9wpEg0Oi42IKBKzDavsa/w0=
