= MailCLI
Rahul Somasunderam <rahul.som@gmail.com>
:toc: left
:binaryname: mailcli
:bintrayHome: https://dl.bintray.com//content/rahulsom/golang/
:linktext: Download

CLI that lets you pipe output to email using SendGrid

== Introduction
Very often you find yourself having to copy the output of asciidoctor and paste it into your mail client only to
realize that it's messed up by then.

Or sometimes you want to run some commands and take their output and automate emails.

May be you're using Exchange and can't really automate email without jumping through hoops.

Well, look no further; we now have `{binaryName}`.

== Getting Started
You will have to sign up for a SendGrid account first. This will require you to use an email address that's not a
public mail server. Once you're done signing up for your account, in your shell profile declare some environment
variables

[source,bash]
----
export SENDGRID_USER=<username>
export SENDGRID_PASS=<password>
export SENDGRID_FROM=sender@example.com
----

You could skip that and set your environment every time you want to run the `{binaryName}` command, but that ends
up getting really painful.

== Installation

You have several options to install {binaryName}

=== Go get

If you have already installed the go sdk on your machine and prefer using `go get`, you can use that.

[source,bash,subs="attributes+"]
----
go get github.com/rahulsom/{binaryName}
----

This is the preferred approach, beacuse you can then update it without giving it much thought.

However, setting up go is not for everyone, so there is the direct download approach.

=== Direct download

NOTE: This is WIP. It hasn't been tested in all platforms. If it does not
work, please raise a bug on github issues.

// image::https://api.bintray.com/packages/rahulsom/golang/mailcli/images/download.svg[link="https://bintray.com/rahulsom/golang/mailcli/_latestVersion"]

[cols="4*"]
|===
|
| 386
| amd64
| arm

| Darwin (Apple Mac)
| {bintrayHome}{binaryname}_{mailcliVersion}_darwin_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_darwin_amd64.zip?direct[{linktext}]
|

| FreeBSD
| {bintrayHome}{binaryname}_{mailcliVersion}_freebsd_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_freebsd_amd64.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_freebsd_arm.zip?direct[{linktext}]

| Debian
| {bintrayHome}{binaryname}_{mailcliVersion}_snapshot_amd64.deb?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_snapshot_armhf.deb?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_snapshot_i386.deb?direct[{linktext}]

| Other Linux
| {bintrayHome}{binaryname}_{mailcliVersion}_linux_386.tar.gz?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_linux_amd64.tar.gz?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_linux_arm.tar.gz?direct[{linktext}]

| MS Windows
| {bintrayHome}{binaryname}_{mailcliVersion}_windows_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_windows_amd64.zip?direct[{linktext}]
|

| NetBSD
| {bintrayHome}{binaryname}_{mailcliVersion}_netbsd_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_netbsd_amd64.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_netbsd_arm.zip?direct[{linktext}]

| OpenBSD
| {bintrayHome}{binaryname}_{mailcliVersion}_openbsd_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_openbsd_amd64.zip?direct[{linktext}]
|

| DragonFly
| {bintrayHome}{binaryname}_{mailcliVersion}_dragonfly_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_dragonfly_amd64.zip?direct[{linktext}]
|

| NaCl
| {bintrayHome}{binaryname}_{mailcliVersion}_nacl_386.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_nacl_amd64p32.zip?direct[{linktext}]
| {bintrayHome}{binaryname}_{mailcliVersion}_nacl_arm.zip?direct[{linktext}]

| Solaris
|
| {bintrayHome}{binaryname}_{mailcliVersion}_solaris_amd64.zip?direct[{linktext}]
|

| Plan 9
| {bintrayHome}{binaryname}_{mailcliVersion}_plan9_386.zip?direct[{linktext}]
|
|

|===

Once you've downloaded the right archive for your platform, make sure the executable is in your path. Then you're
all set.


//==== Other files
//
//* link:.goxc-temp/control.tar.gz[control.tar.gz]
//* link:.goxc-temp/data.tar.gz[data.tar.gz]

== Usage

=== Help
To see help, say

[source,bash,subs="attributes+"]
----
{binaryName} -h
----

=== Text

[source,bash,subs="attributes+"]
----
cat testresult.txt | {binaryName} -to "foo@bar.com" -s "Test Result"
----

=== HTML

[source,bash,subs="attributes+"]
----
cat document.html | {binaryName} -to "foo@bar.com" -s "What's for lunch" -html
----

=== Asciidoctor

If you have asciidoctor installed, you could pipe that to an email too.

[source,bash,subs="attributes+"]
----
asciidoctor index.adoc -o - | {binaryName} -to "foo@bar.com" -s "MailCLI Docs" -html
----

== Email Address Format

These are acceptable formats for emails

----
user@domain.com
Name <user@domain.com>
Very Long Name <user@domain.com>
"Name in quotes" <user@domain.com>
----

If you have multiple recipients in a field, you must separate them using commas.
*Not seimcolons*

[source,bash,subs="attributes+"]
----
cat testresult.txt | {binaryName} \
        -to "foo@bar.com, Private Snafu<snafu@tarfu.com>, Fubar@tarfu.com" \
        -s "Test Result"
----
